### ISSUE TITLE
Is this an improved screen space technique?

### ISSUE THREAD

**Issue by juangea** [GameTechDev/XeGTAO#2]
Is this an improved screen space technique?

I think I understood this, but I prefer to ask :)

**Comment by fstrugar** [comment]
It's an implementation of the screen space technique from 2016 (https://www.activision.com/cdn/research/Practical_Real_Time_Strategies_for_Accurate_Indirect_Occlusion_NEW%20VERSION_COLOR.pdf) which is still probably the best screen space AO+ approach. We've done a couple of upgrades but the core is essentially the same as described in the paper. 
I've changed the first sentence in the README.md to explicitly say that it's screen space :) All the best!
