### ISSUE TITLE
why the spatial denoise kernal size is 5x5?

### ISSUE THREAD

**Issue by ZhangRuFu** [GameTechDev/XeGTAO#6]
thank you very much for providing this implementation and improve for GTAO :)
I‘m confused about the kernal size when i read the source in XeGTAO_Denoise function
![image](https://user-images.githubusercontent.com/17218243/153171081-d7603868-e61a-4a79-b097-0507eb97a649.png)

Is it a 3x3 spatial kernal size actually...?

**Comment by fstrugar** [comment]
Hi, thanks for the kind words! In one of the last changes, the kernel was reduces from 5x5 to 3x3, but is (optionally) ran twice. When applied twice it is still effectively covering a 5x5 area :)

[note: I left Intel and am no longer maintaining this repository - hopefully Intel will find a suitable replacement]

**Comment by ZhangRuFu** [comment]
Oh, I get it, thank you for your reply
